# Generated by Django 4.2.8 on 2023-12-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="taskname",
            field=models.CharField(max_length=300),
        ),
    ]
